package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'GenerateTestmodels'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("GenerateTestmodels")) {
    params {
        add {
            param("env.PIXI_CACHE_DIR", "/u/svc-teamcity-ansible/.cache")
        }
    }
}
