package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Ribasim_MakeGitHubRelease'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Ribasim_MakeGitHubRelease")) {
    dependencies {
        expect(RelativeId("Linux_TestRibasimBinaries")) {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }
        }
        update(RelativeId("Linux_TestRibasimBinaries")) {
            snapshot {
                reuseBuilds = ReuseBuilds.ANY
            }
        }

    }
}
