package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Windows_BuildMsix'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Windows_BuildMsix")) {
    check(paused == true) {
        "Unexpected paused: '$paused'"
    }
    paused = false

    check(artifactRules == """ribasim\build\ribasim_windows.msix""") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "ribasim/build/ribasim_windows.msix => ribasim_windows.zip"
}
