package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Ribasim_Linux'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Ribasim_Linux")) {
    check(archived == false) {
        "Unexpected archived: '$archived'"
    }
    archived = true
}
