package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Ribasim1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("Ribasim1")
    name = "Ribasim (1)"
    url = "https://github.com/Deltares/Ribasim"
    branch = "main"
    branchSpec = """
        +:refs/heads/*
        +:refs/tags/*
        -:refs/heads/gh-pages
    """.trimIndent()
    useTagsAsBranches = true
    authMethod = password {
        userName = "teamcity-deltares"
        password = "credentialsJSON:abf605ce-e382-4b10-b5de-8a7640dc58d9"
    }
}))

