"""
Generate Pandera Schemas from all autogenerated Pydantic Models

These classes have Schema as a postfix, so Ribasim.models.PumpStatic
becomes Ribasim.node_types.PumpStaticSchema.
"""
import inspect
import sys

import pandera as pa
from pandera.engines.pandas_engine import PydanticModel

from ribasim import models


def gen_schema(name, cls):
    classname = f"{name}Schema"
    setattr(
        sys.modules[__name__],
        classname,
        type(
            classname,
            (pa.DataFrameModel,),
            {
                "Config": type(
                    f"{classname}.Config",
                    (),
                    {"dtype": PydanticModel(cls), "coerce": True},
                )
            },
        ),
    )


for name, cls in inspect.getmembers(models, inspect.isclass):
    gen_schema(name, cls)
