FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

ARG PIXI_VERSION=v0.49.0
ARG JULIA_VERSION=1.9.4

RUN curl -L -o /usr/local/bin/pixi -fsSL --compressed "https://github.com/prefix-dev/pixi/releases/download/${PIXI_VERSION}/pixi-$(uname -m)-unknown-linux-musl" \
    && chmod +x /usr/local/bin/pixi \
    && pixi info

    # install julia
    RUN curl -L -o julia.tar.gz -fsSL "https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-${JULIA_VERSION}-linux-x86_64.tar.gz" \
        && tar -xzf julia.tar.gz \
        && mv julia-${JULIA_VERSION} /opt/julia \
        && rm julia.tar.gz \
        && ln -s /opt/julia/bin/julia /usr/local/bin/julia

# set some user and workdir settings to work nicely with vscode
USER vscode
WORKDIR /home/vscode

RUN echo 'eval "$(pixi completion -s bash)"' >> /home/vscode/.bashrc
