---
title: "FractionalFlow"
---

FractionalFlow allows splitting a flow into multiple fractions, as a way to model river bifurcations.
It cannot be directly behind a Basin since that doesn't prescribe a flow.

For example, if you want to send 20% of the flow over a TabulatedRatingCurve to one downstream Basin, and the rest to another, you can do that as follows:

```{mermaid}
flowchart LR
    Basin#1[Basin #1] --> TabulatedRatingCurve
    TabulatedRatingCurve -->|1.0| FractionalFlow
    FractionalFlow -->|0.2| Basin#2[Basin #2]
    FractionalFlow -->|0.8| Basin#3[Basin #3]
```

The FractionalFlow node is useful if you know the fractions at which available flows are divided.
It should be noted that there are other ways to bifurcate flows that do not involve a FractionalFlow, with multiple outflows from a single Basin:

```{mermaid}
flowchart LR
    Basin#1[Basin #1] --> TabulatedRatingCurve#1[TabulatedRatingCurve #1]
    Basin#1[Basin #1] --> TabulatedRatingCurve#2[TabulatedRatingCurve #2]
    TabulatedRatingCurve#1[TabulatedRatingCurve #1] --> Basin#2[Basin #2]
    TabulatedRatingCurve#2[TabulatedRatingCurve #2] --> Basin#3[Basin #3]
```

# Tables

# Static

Lets a fraction (in [0,1]) of the incoming flow through.

column        | type    | unit         | restriction
------------- | ------- | ------------ | -----------
node_id       | Int32   | -            | sorted
control_state | String  | -            | (optional) sorted per node_id
fraction      | Float64 | -            | in the interval [0,1]
