---
title: "Contributing"
---

Ribasim welcomes contributions.

There is developer documentation for the [Julia core](core.qmd), the [Basic Model Interface (BMI)](bmi.qmd), [Python tooling](python.qmd), and the [QGIS plugin](qgis.qmd).
A guide on how to add a new node type to both is written in [adding node types](addnode.qmd).
[Release process](release.qmd) describes the steps to follow when creating a new Ribasim release.

# Set up the developer environment

## Clone Ribasim

In order to have the Ribasim repository locally available, you can clone it with Git.
Git can be installed from [git-scm.com](https://git-scm.com/downloads).
Once installed, run the following command at a directory of your choice:

In order to have the Ribasim repository locally available, run the following command at a directory of your choice:

```sh
git clone https://github.com/Deltares/Ribasim.git
```

To continue with the following steps, make the root of the repository your working directory by running

```sh
cd Ribasim
```

## Setting up pixi

First, set up pixi as described on their getting started [page](https://prefix.dev/docs/pixi/overview).

Then set up the environment by running the following commands:

```sh
pixi run install
```

This will automatically install all required packages for development.
Our pixi environment also provides an instance of Julia and QGIS.
These will not conflict with any pre-installed applications, as long as you have the pixi environment enabled.
You can do this in a terminal by calling `pixi shell`, or starting programs with `pixi run julia`, or `pixi run qgis`.
This is also the way that we start visual studio code: `pixi run code .`.
