package patches.templates

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'GitHubIntegrationTemplate'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("GitHubIntegrationTemplate")) {
    vcs {
        remove(DslContext.settingsRoot.id!!, ". => ribasim")
        add(RelativeId("Ribasim1"), ". => ribasim")
    }
}
