---
title: "Outlet"
---

The Outlet lets water flow downstream with a prescribed flow rate.
It is similar to the Pump, except that water only flows down, by gravity.

When PID controlled, the Outlet must point towards the controlled Basin in terms of links.

# Tables

## Static

column                | type    | unit                   | restriction
---------             | ------- | ---------------------- | -----------
node_id               | Int32   | -                      |
control_state         | String  | -                      | (optional)
active                | Bool    | -                      | (optional, default true)
flow_rate             | Float64 | $\text{m}^3/\text{s}\$ | non-negative
min_flow_rate         | Float64 | $\text{m}^3/\text{s}\$ | (optional, default 0.0)
max_flow_rate         | Float64 | $\text{m}^3/\text{s}\$ | (optional)
min_upstream_level    | Float64 | $\text{m}$             | (optional)
max_downstream_level  | Float64 | $\text{m}$             | (optional)

## Time

This table is the transient form of the `Outlet` table.
With this the flow_rate can be updated over time. In between the given times the
flow_rate is interpolated linearly, and outside the flow rate is constant given by the
nearest time value.
Note that a `node_id` can be either in this table or in the static one, but not both.

column                | type    | unit                   | restriction
---------             | ------- | ---------------------- | -----------
node_id               | Int32   | -                      |
time                  | DateTime| -                      |
control_state         | String  | -                      | (optional)
flow_rate             | Float64 | $\text{m}^3/\text{s}\$ | non-negative
min_flow_rate         | Float64 | $\text{m}^3/\text{s}\$ | (optional, default 0.0)
max_flow_rate         | Float64 | $\text{m}^3/\text{s}\$ | (optional)
min_upstream_level    | Float64 | $\text{m}$             | (optional)
max_downstream_level  | Float64 | $\text{m}$             | (optional)

# Equations

The Outlet is very similar to the Pump, but it has an extra [reduction factor](/reference/node/basin.qmd#sec-reduction-factor) for physical constraints:

$$
Q = \mathrm{clamp}(\phi Q_\text{set}, Q_{\min}, Q_{\max})
$$

- $Q$ is the realized Outlet flow rate.
- $Q_\text{set}$ is the Outlet's target `flow_rate`.
- $Q_{\min}$ and $Q_{\max}$ are the Outlet `min_flow_rate` and `max_flow_rate`.
- $\phi$ is the reduction factor, which smoothly reduces flow based on all of these criteria:
  - The upstream volume is below $10 m^3$.
  - The upstream level is less than $0.02 m$ above the downstream level.
  - The upstream level is below `min_upstream_level` + $0.02 m$
  - The downstream level is above `max_downstream_level` - $0.02 m$
