---
title: "TabulatedRatingCurve"
---

A TabulatedRatingCurve determines outflow from a Basin by looking up the flow rate that corresponds to the current upstream level from a rating curve.
The TabulatedRatingCurve takes a rating curve as input.
Use it for instance to model flow over a weir.

# Tables

## Static

column               | type    | unit                  | restriction
-------------        | ------- | --------------------- | -----------
node_id              | Int32   | -                     |
control_state        | String  | -                     | (optional)
active               | Bool    | -                     | (optional, default true)
max_downstream_level | Float64 | $\text{m}$            | (optional)
level                | Float64 | $\text{m}$            | unique
flow_rate            | Float64 | $\text{m}^3/\text{s}$ | start at 0, increasing

### Interpolation

The $Q(h)$ relationship of a tabulated rating curve is defined as a smoothed linear interpolation.

```{julia}
# | code-fold: true
using DataInterpolations
using Plots

level = [12.0, 12.2, 12.5, 13.0]
flow = [0.0, 0.5, 2.5, 8.0]

level_aug = copy(level)
flow_aug = copy(flow)

pushfirst!(level_aug, first(level) - 1.0)
pushfirst!(flow_aug, 0.0)

itp = SmoothedLinearInterpolation(
    flow_aug,
    level_aug;
    extrapolation_right = DataInterpolations.ExtrapolationType.Linear,
)

level_eval = range(first(level), last(level); length = 1000)
flow_eval = itp.(level_eval)

level_extrap_left = [first(level) - 0.3, first(level)]
flow_extrap_left = itp.(level_extrap_left)

level_extrap_right = [last(level), last(level) + 0.3]
flow_extrap_right = itp.(level_extrap_right)

c = :blue
plot(
    level_eval,
    flow_eval;
    c,
    label = "interpolation",
    xticks = false,
    yticks = false,
    left_margin = 5Plots.mm,
)
plot!(level_extrap_left, flow_extrap_left; ls = :dash, c, label = "extrapolation")
plot!(level_extrap_right, flow_extrap_right; ls = :dash, c, label = "")
scatter!(level, flow; c, label = "data", markeralpha = 0.25)
xlabel!("level")
ylabel!("flow")
xlims!(first(level) - 0.2, last(level) + 0.2)
```

Below the lowest given level of 12.0, the flow rate is kept at 0.
Between given levels the flow rate is interpolated linearly (with some smoothing).
Above the maximum given level of 13.0, the flow rate keeps increases linearly according to the slope of the last segment.

For tabulated rating curves with a fixed maximum value (e.g. max capacity of a weir), enter a new row and re-enter the maximum flow_rate at a higher level:

node_id | level  | flow_rate
------- | ------ | ----------
      2 | 12.0   | 0.0
      2 | 12.2   | 0.5
      2 | 12.5   | 2.5
      2 | 13.0   | 8.0
      2 | 13.1   | 8.0

Now this tabulated rating curve node has a flow rate of 8.0 $\text{m}^3/\text{s}$ for for all levels 13.0 or higher.

The flow rate is not allowed to decrease with higher levels.
If you wish to e.g. simulate the (partial) closing of a weir when the water level exceeds a certain threshold, you can use and Outlet with a control node to set flow rates.

:::{.callout-note}
The data in the function table is not interpolated exactly linearly. On an interval around each data point the linear interpolation is replaced by a spline section. This interval is given by 12.5% of the distance between the input values on either side of the data points.
:::

## Time

This table is the transient form of the `TabulatedRatingCurve` table.
The only difference is that a time column is added.
With this the rating curves can be updated over time.
The `max_downstream_level` currently cannot be updated over time.
Note that a `node_id` can be either in this table or in the static one, but not both.

column               | type     | unit                  | restriction
-------------------- | -------  | --------------------- | -----------
node_id              | Int32    | -                     |
time                 | DateTime | -                     |
level                | Float64  | $\text{m}$            |
flow_rate            | Float64  | $\text{m}^3/\text{s}$ | non-negative
max_downstream_level | Float64  | $\text{m}$            | (optional)

# Equations

The TabulatedRatingCurve is a tabulation of a Basin's discharge behavior.
It describes a piecewise linear relationship between the Basin's level and its discharge.
It can be understood as an empirical description of a Basin's properties.
This can include a weir, but also the lumped hydraulic behavior of the upstream channels.

$$
Q = \phi f(h)
$$

Where:

- $h$ is the upstream water level
- $f$ is a piecewise linear function describing the given rating curve $Q(h)$
- $\phi$ is the reduction factor, which smoothly reduces flow based on all of these criteria:
  - The upstream volume is below the equivalent of a water depth of $10 \;\text{cm}$.
  - The upstream level is less than $0.02 \;\text{m}$ above the downstream level.
  - The downstream level is above `max_downstream_level` - $0.02 \;\text{m}$
