# Changelog

All notable changes to this project will be documented in this file.
The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),

## [Unreleased]

## [v2025.3.0] - 2025-04-14

The only breaking change in this release is to disallow connecting a single FlowBoundary to multiple Basins.
There are large improvements in the ability to visualize results on the map in QGIS.
We also welcome the Junction node to the family, which will help laying out networks in a recognizable manner.

### Added
- Add spatio-temporal results layers to QGIS. [#2208](https://github.com/Deltares/Ribasim/pull/2208)
- Add topological (straight line) link view toggle to QGIS. [#2208](https://github.com/Deltares/Ribasim/pull/2208)
- Added [Junction](https://ribasim.org/reference/node/junction.html) node type. [#2175](https://github.com/Deltares/Ribasim/pull/2175)
- Write results and log bottlenecks also on an interrupt or crash. [#2191](https://github.com/Deltares/Ribasim/pull/2191) [#2200](https://github.com/Deltares/Ribasim/pull/2200)
- Log computation time and save it to `solver_stats.arrow`. [#2209](https://github.com/Deltares/Ribasim/pull/)
- Experimental support for writing the model network and results into files used by Delft-FEWS, [`model.to_fews`](`https://ribasim.org/reference/python/Model.html#ribasim.Model.to_fews`). [#2161](https://github.com/Deltares/Ribasim/pull/2161)
- Document [`results/concentration.arrow`](https://ribasim.org/reference/usage.html#concentration---concentration.arrow). [#2165](https://github.com/Deltares/Ribasim/pull/2165)

### Changed
- Allow max 1 outflow neighbour for FlowBoundary. [#2192](https://github.com/Deltares/Ribasim/pull/2192)
- Automatic differentiation is enabled by default again, `autodiff = true`, leading to better performance. [#2137](https://github.com/Deltares/Ribasim/pull/2137) [#2183](https://github.com/Deltares/Ribasim/pull/2183)

## [v2025.2.0] - 2025-03-10

In this release, time is of the essence. We now support dynamic Pumps and Outlets, as well as DiscreteControl thresholds.
For each node, timeseries can be marked as cyclic, such that yearly recurring timeseries can be easily used without repetition.
We also developed tools to compare model input in Python.

The most visible change is the renaming of Edge to Link. Like always, existing models are migrated to the new version by reading them with Ribasim Python, and writing out the updated version. For now in Python `model.edge` will continue to work to ease the transition.

### Added

- Check Model equality in Python. [#2057](https://github.com/Deltares/Ribasim/pull/2057)
- Compare two models in Python. [#2080](https://github.com/Deltares/Ribasim/pull/2080)
- Support cyclic input timeseries. [#2081](https://github.com/Deltares/Ribasim/pull/2081) [#2102](https://github.com/Deltares/Ribasim/pull/2102)
- Time dependent `greater_than` thresholds in DiscreteControl. [#2079](https://github.com/Deltares/Ribasim/pull/2079)
- Validation error on connector nodes having the same from and to Basin. [#2112](https://github.com/Deltares/Ribasim/pull/2112)
- Support time dependent Pump and Outlet tables. [#2110](https://github.com/Deltares/Ribasim/pull/2110)

### Changed
- Edges are now called links. [#2023](https://github.com/Deltares/Ribasim/pull/2023)
- All geometries are coerced to 2D. [#2111](https://github.com/Deltares/Ribasim/pull/2111)

### Fixed
- Faster initialization of large tables. [#2026](https://github.com/Deltares/Ribasim/issues/2026)
- Declare incompatibility with Pandera v0.23+. [#2120](https://github.com/Deltares/Ribasim/issues/2120)
- Decrease the smoothing around `Δh = 0` in ManningResistance. [#2136](https://github.com/Deltares/Ribasim/issues/2136)

## [v2025.1.0] - 2025-01-17

The first release of 2025 makes the Ribasim core more robust and stable, and speeds up
initialization for large models. The biggest new feature is the experimental support for
calculating tracers in Ribasim directly, which will hopefully make it easier to track where
the water resources are heading.

### Added
- Remove Z coordinate on constructing Node in Python. [#1986](https://github.com/Deltares/Ribasim/pull/1986)
- Add "Basin / subgrid_time" table. [#1975](https://github.com/Deltares/Ribasim/pull/1975)
- Sign Ribasim binaries. [#2007](https://github.com/Deltares/Ribasim/pull/2007)
- Experimental: Calculate tracer concentrations internally. [#1849](https://github.com/Deltares/Ribasim/pull/1849)
- Document [parsing Delwaq results](https://ribasim.org/guide/delwaq). [#1845](https://github.com/Deltares/Ribasim/pull/1845)

### Removed
- Drop Python 3.10 support. [#2012](https://github.com/Deltares/Ribasim/pull/2012)

### Changed
- Allocation: optimize per source. [#1927](https://github.com/Deltares/Ribasim/pull/1927)
- The Edge table no longer supports `subnetwork_id`; this is automatically inferred. [#1956](https://github.com/Deltares/Ribasim/pull/1956)

### Fixed
- ManningResistance is more stable around Δh=0. [#1896](https://github.com/Deltares/Ribasim/pull/1896)
- Fixes to Delwaq model generation. [#1903](https://github.com/Deltares/Ribasim/pull/1903) [#1917](https://github.com/Deltares/Ribasim/pull/1917) [#1948](https://github.com/Deltares/Ribasim/pull/1948)
- Add step limiter to avoid negative flows or too large flows. [#1911](https://github.com/Deltares/Ribasim/pull/1911) [#1912](https://github.com/Deltares/Ribasim/pull/1912)
- Fix README.md in builds. [#1935](https://github.com/Deltares/Ribasim/pull/1935) [#1938](https://github.com/Deltares/Ribasim/pull/1938)
- Speed up initialization. [#1977](https://github.com/Deltares/Ribasim/pull/1977)
- Automatically name index in Python. [#1974](https://github.com/Deltares/Ribasim/pull/1974)
- Table sorting related fixes. [#2003](https://github.com/Deltares/Ribasim/pull/2003)

## [v2024.11.0] - 2024-10-08

This major new release contains many improvements.
A new formulation allows much smaller water balance errors, which is combined with several performance improvements.
Ribasim Python does more validation that was previously only done in the core.
The Ribasim QGIS plugin now sets the relations between tables for easier model inspection.
Adding `min_upstream_level` and `max_downstream_level` to Pump and Outlet means DiscreteControl is often no longer needed.
The most significant breaking change is making the `node_id` and `edge_id` the index of the Node and Edge table; these need to be globally unique.

Starting from this release Ribasim is labeled as beta software.
Since development is currently mainly driven by applications in the Dutch water system, we expect that addition work needs to be done for general use outside the Netherlands.

For coupled simulation with MODFLOW and/or MetaSWAP, this release is part of the [iMOD Coupler](https://deltares.github.io/iMOD-Documentation/coupler.html), specifically release [v2024.4.0](https://github.com/Deltares/imod_coupler/releases/tag/v2024.4.0)

### Added

- Support discrete control based on an external concentration condition. [#1660](https://github.com/Deltares/Ribasim/pull/1660)
- Add `results/solver_stats.arrow` with solver statistics over time. [#1677](https://github.com/Deltares/Ribasim/pull/1677)
- Add icon to `ribasim.exe` on Windows. [#1712](https://github.com/Deltares/Ribasim/pull/1712)
- Save QGIS styling in the model database. [#1713](https://github.com/Deltares/Ribasim/pull/1713)
- Add Delwaq coupling guide. [#1619](https://github.com/Deltares/Ribasim/pull/1619)
- Solver speedup due to backtracking relaxation. [#1761](https://github.com/Deltares/Ribasim/pull/1761)
- Reject adding a duplicate edge in Python. [#1719](https://github.com/Deltares/Ribasim/pull/1719)
- Support transient UserDemand return factor. [#1727](https://github.com/Deltares/Ribasim/pull/1727)
- Document the interpolation of input data. [#1720](https://github.com/Deltares/Ribasim/pull/1720)
- Automate Jacobian sparsity detection. [#1606](https://github.com/Deltares/Ribasim/pull/1606)
- Support specifying the `edge_id` as `model.edge.add(a, b, edge_id=5)`. [#1737](https://github.com/Deltares/Ribasim/pull/1737)
- Use [https://ribasim.org/](https://ribasim.org/) to host our documentation. [#1736](https://github.com/Deltares/Ribasim/pull/1736)
- Validate geometry types in Python. [#1760](https://github.com/Deltares/Ribasim/pull/1760)
- Add relationships between tables in QGIS. [#1755](https://github.com/Deltares/Ribasim/pull/1755)
- Support migrating from older Ribasim versions in Python. [#1764](https://github.com/Deltares/Ribasim/pull/1764)
- Add quick start guide to docs. [#1787](https://github.com/Deltares/Ribasim/pull/1787)
- Add `min_upstream_level` and `max_downstream_level` to Pump and Outlet. [#1792](https://github.com/Deltares/Ribasim/pull/1792)
- Add `max_downstream_level` to TabulatedRatingCurve. [#1795](https://github.com/Deltares/Ribasim/pull/1795)
- Validate edge connections in Python. [#1765](https://github.com/Deltares/Ribasim/pull/1765)
- Add low storage reduction factor to ManningResistance. [#1796](https://github.com/Deltares/Ribasim/pull/1796)

### Changed

- Refactor of the core to ensure smaller water balance errors. [#1819](https://github.com/Deltares/Ribasim/pull/1819)
- Make `node_id` globally unique. [#1717](https://github.com/Deltares/Ribasim/pull/1717)
- Make the Node ID the index of the Node table, and Edge ID for Edge. [#1737](https://github.com/Deltares/Ribasim/pull/1737)
- Make more Python functions private. [#1702](https://github.com/Deltares/Ribasim/pull/1702)
- Put the contents of the CLI zips in a folder. [#1722](https://github.com/Deltares/Ribasim/pull/1722)
- Changed water balance error definition. [#1767](https://github.com/Deltares/Ribasim/pull/1767)
- Disallow missing priority parameter when using allocation. [#1745](https://github.com/Deltares/Ribasim/pull/1745)
- Rename Outlet's `min_crest_level` to `min_upstream_level`. [#1788](https://github.com/Deltares/Ribasim/pull/1788)
- Only allow flow under gravity in TabulatedRatingCurve. [#1795](https://github.com/Deltares/Ribasim/pull/1795)
- Use `dtype_backend="pyarrow"` for Pandas DataFrames. [#1781](https://github.com/Deltares/Ribasim/pull/1781)

### Fixed
- Remove oscillations in ManningResistance. [#1750](https://github.com/Deltares/Ribasim/pull/1750)
- Fix GeoPandas CRS warning. [#1810](https://github.com/Deltares/Ribasim/pull/1810)

## [v2024.10.0] - 2024-07-23

For this release we said goodbye to the problematic FractionalFlow node, but welcome the ContinuousControl as a long requested feature.

### Added
- Control: Add ContinuousControl node type. [#1602](https://github.com/Deltares/Ribasim/pull/1602)
- Control: Support listening to flow through connector nodes. [#1594](https://github.com/Deltares/Ribasim/pull/1594)
- Validate that TabulatedRatingCurve levels are above Basin bottom. [#1607](https://github.com/Deltares/Ribasim/pull/1607)
- Validate that Outlet minimum upstream levels are above Basin bottom. [#1607](https://github.com/Deltares/Ribasim/pull/1607)
- Always show convergence bottlenecks. [#1636](https://github.com/Deltares/Ribasim/pull/1636)
- Docstrings for Ribasim Python. [#1643](https://github.com/Deltares/Ribasim/pull/1643)
- Allocate to UserDemand from directly connected Basin if possible. [#1581](https://github.com/Deltares/Ribasim/pull/1581)
- Add `basin_state.arrow` results. [#1626](https://github.com/Deltares/Ribasim/pull/1626)
- Also write stacktraces to `ribasim.log`. [#1653](https://github.com/Deltares/Ribasim/pull/1653)

### Changed
- Require QGIS 3.34 (LTR) or newer for Ribasim QGIS plugin.

### Fixed
- Compatibility with latest NumPy, Pandera and PyArrow releases. [#1618](https://github.com/Deltares/Ribasim/pull/1618)
- LevelDemand can now be without `min_level` or `max_level`. [#1629](https://github.com/Deltares/Ribasim/pull/1629)

### Removed
- Removed unused urban runoff variable from Basin. [#1611](https://github.com/Deltares/Ribasim/pull/1611)
- Removed unneeded static table from Terminal. [#1624](https://github.com/Deltares/Ribasim/pull/1624)
- Removed FractionalFlow node. [#1616](https://github.com/Deltares/Ribasim/pull/1616)

## [v2024.9.0] - 2024-06-20

### Added
- Support for concentration state and time for Delwaq coupling.
- Show exact commit on `ribasim --version` if it is not a release. [#1479](https://github.com/Deltares/Ribasim/pull/1479)

### Changed
- Optimized performance.
- Documentation has been overhauled to be more user-friendly.
- Stricter TabulatedRatingCurve validation. [#1469](https://github.com/Deltares/Ribasim/pull/1469)
- Stricter Basin / profile validation. [#1486](https://github.com/Deltares/Ribasim/pull/1486)
- Allocation objective function now gives equal ratios during shortage. [#1386](https://github.com/Deltares/Ribasim/pull/1386)

### Fixed
- Don't require unique node IDs. [#1513](https://github.com/Deltares/Ribasim/pull/1513)
- Fix QGIS crash on plugin initialization. [#1580](https://github.com/Deltares/Ribasim/pull/1580)

## [v2024.8.0] - 2024-05-14

### Added

- There is more validation on the edges. [#1434](https://github.com/Deltares/Ribasim/pull/1434)
- If the model does not converge and the used algorithm supports it, we log which Basins don't converge. [#1440](https://github.com/Deltares/Ribasim/pull/1440)

### Changed

- If negative storages inadvertently happen, we now throw an error. [#1425](https://github.com/Deltares/Ribasim/pull/1425)
- Users of the QGIS plugin need to remove the old version to avoid two copies due to [#1453](https://github.com/Deltares/Ribasim/pull/1453).

### Fixed

- Performance improvements have been a focus of this release, giving up to 10x faster runs. [#1433](https://github.com/Deltares/Ribasim/pull/1433), [#1436](https://github.com/Deltares/Ribasim/pull/1436), [#1438](https://github.com/Deltares/Ribasim/pull/1438), [#1448](https://github.com/Deltares/Ribasim/pull/1448), [#1457](https://github.com/Deltares/Ribasim/pull/1457)
- The CLI exe is now always in the root of the zip and makes use of the libribasim shared library. [#1415](https://github.com/Deltares/Ribasim/pull/1415)
