## Test cases

In our test cases, we will work with the Dutch national groundwater model
(LHM). For testing, we simplify the top boundary conditions to just three
surface water "systems", from large to small:

1. Primary
2. Secondary
3. Tertiary

(Note: Bach has no knowledge of these systems. Any basin is represented by a
single volume.)

These systems are be separated due to their relatively small size in comparison
with relatively coarse cells of the groundwater model: most cells in the LHM
contain more than one surface water, and are included via representative
parameters which take the physical scaling into account.

In case of sufficiently small cell sizes, no overlap occurs and all surface
waters can be represented in a single grid.

For the purposes of testing, we have not created empirical volume-level
relationships for the surface water of every cell. Instead, we have chosen an
(over)simplified representation over the hydraulic properties, which makes it
easy to verify the behavior of Bach and the coupling procedures:

1. Primary, secondary, and tertiary systems have a rectangular profile: the
  area of the surface water does not change with water level or volume.
2. Water depth is constant for a system within a basin.
3. Water depth increases linearly with volume. (This follows from 1.)
4. Water depth is distributed across the systems in a geometric progression:
  when the tertiary system contains 0.1 m of water, the secondary system contains
0.2 m, and the primary system contains 0.4 m.
5. Water depth is 0.0 m for all systems when basin volume is 0.0. (This follows from 4.)
6. The distribution of water occurs according to the surface water area (width
  times length) used for the LHM parametrization of river bed conductance.
  
An example of the resulting parameters for a single cell is shown in
@tbl-hupsel-v-h. The first row shows the water levels when the basin is empty.
The level for primary, secondary, and tertiary are equal to the bottom
elevation of the surface waters. The second row shows the volume and levels for
water depths of 0.4, 0.2, and 0.1 m. The third row shows the volume and levels
for a tenfold larger volume. This results in implausible water levels with
depths of 4.0, 2.0 and 1.0 m; the water level in the primary system is over
two meters higher than in the tertiary system. In reality, the surface waters
would overflow and surface ponding would occur; this mechanism is ignored
in the test cases for the sake of simplicity.

| Volume (m3) | Primary (m NAP) | Secondary (m NAP) | Tertiary (m NAP) |
|-------------|-----------------|-------------------|------------------|
| 0.0         | 25.65           | 25.83             | 26.60            |
| 6843.1      | 26.05           | 26.03             | 26.70            |
| 68431.0     | 29.65           | 27.83             | 27.60            |

: Volume-level table for a single cell in the Hupsel basin. {#tbl-hupsel-v-h}

Image ... shows the volume of the first row of the cell based input for the
primary system. Symbology is set to unique values.

# Test case: Hupsel

To test the coupling, the following simulations have been setup and run:

1. A standalone MODFLOW6 run of sequential steady-states (i.e. no storage) with
  differing groundwater recharge values.
2. A coupled run where the MODFLOW6 stages are updated through the

From these tests, we expect the following behavior:

1. Drainage terms should remain largely the same when the water level is lowered in a steady-state:
  the amount of recharge is fixed, and this is locally drained.
2. In case of negative recharge (evapotranspiration), infiltration occurs in the surface waters.
  Infiltration should be zero when the basin volume is 0.

Figure ... shows the water balance of steady-state for submodel of the
LHM that has been by selecting the cells belonging to the district containing
the Hupsel catch, the Berkel. The Hupsel basin show the expected behavior:
in terms of incoming flows, most is precipitation with a minor part lateral
inflow from higher areas. In terms of outgoing flows, most of the precipitation
ends up in the surface water, primarily in the many ditches of the tertiary
system. Only a relatively small part of the water leaves the basin via the
groundwater. Interbasin flows through the groundwater form such a minor role,
as the aquifer is thin and transmissivity is limited.

## Budgets

Table ... shows the budgets computed by MODFLOW6 per primary, secondary, and
tertiary system. These are compared to the budget computed by the coupling
procedure, which uses equation ...

As expected, these numbers match exactly.

## Zero volume

# Test case: de Tol

Figure ... shows the water balance of steady-state for a submodel of the LHM
for the Polder de Tol and its surroundings. While groundwater recharge is the
dominant in going flow, lateral groundwater flow (over the entire depth of
the groundwater model) is a sizable inflow for the area; the larger lateral
inflow shows that De Tol is a net receiver of groundwater. In contrast to the
Hupsel, the tertiary system is almost entirely absent: drainage occurs not
through ephemeral tertiary ditches, but by the permanently water-bearing
ditches of the primary and secondary system instead. 

Currently, ModelingToolkit takes control of the timestepping. At specified
times, basin volumes are converted to MODFLOW6 boundary condition levels (via
so-called ContinuousCallbacks), and the groundwater equations are solved to
convergence. The drainage and infiltration budgets are then aggregated per
basin, and set for Bach. Bach then proceends with the next timestep.
