flowchart TB
modeler([Modeler]):::user

api["Ribasim Python API\n[python]"]:::system
modeler-->|prepare model|api

ribasim["Ribasim\n[julia]"]:::system
modeler-->|start|ribasim

subgraph qgisBoundary[QGIS]
    QGIS[QGIS Application]:::system_ext
    qgisPlugin["Ribasim QGIS plugin\n[python]"]:::system
    QGIS-->qgisPlugin
end
modeler-->|prepare model|qgisBoundary

model[("input model data\n[toml + geopackage + arrow]")]:::system
qgisPlugin-->|read/write|model
api-->|read/write|model
ribasim-->|simulate|model

output[("simulation output\n[arrow]")]:::system
ribasim-->|write|output

class qgisBoundary boundary

%% class definitions for C4 model
classDef default stroke-width:1px,stroke:white,color:white;
classDef system fill:#1168bd;
classDef user fill:#08427b;
classDef system_ext fill:#999999;
classDef boundary fill:transparent,stroke-dasharray:5 5,stroke:black,color:black;
