name: Julia auto update
on:
  schedule:
    # At 03:00 on day 2 of the month
    - cron: "0 3 2 * *"
  # on demand
  workflow_dispatch:
permissions:
  contents: read
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          pixi-version: "latest"
      - name: Update Julia manifest file
        run: |
          pixi run install-julia
          pixi run update-manifest-julia
          pixi run generate-sbom-ribasim-core
        env:
          JULIA_PKG_PRECOMPILE_AUTO: "0"
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.CI_PR_PAT }}
          branch: update/julia-manifest
          title: Update Julia manifest
          commit-message: "Update Julia manifest"
          body-path: .pixi/update-manifest-julia.md
          author: "GitHub <noreply@github.com>"
