name: Update Pixi lockfile
permissions:
  contents: read
on:
  schedule:
    # At 03:00 on day 3 of the month
    - cron: "0 3 3 * *"
  # on demand
  workflow_dispatch:
jobs:
  pixi-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0 # v0.9.5
        with:
          pixi-version: "latest"
          run-install: false
      - name: Update lockfiles
        run: |
          set -o pipefail
          pixi update --json | pixi exec pixi-diff-to-markdown >> diff.md
          pixi run generate-sbom-ribasim-python
      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.CI_PR_PAT }}
          commit-message: Update pixi lockfile
          title: Update pixi lockfile
          body-path: diff.md
          branch: update/pixi-lock
          base: main
          delete-branch: true
          add-paths: pixi.lock, Ribasim-python.spdx.json
