name: Prek
on:
  pull_request:
  merge_group:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: prefix-dev/setup-pixi@f00437f565399d418b0acc85936d12c1fb668347 # v0.10.1
        with:
          pixi-version: "latest"
      - name: Install prek hooks
        run: pixi run install-prek
      - name: Run prek on all files
        run: pixi run prek-run
