name: Prek
on:
  pull_request:
  merge_group:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          pixi-version: "latest"
      - name: Install prek hooks
        run: pixi run install-prek
      - name: Run prek on all files
        run: pixi run prek-run
