name: Python Codegen
on:
  push:
    branches: [main]
    paths: ["core/**", "python/**", "pixi.toml", "pixi.lock"]
    tags: ["*"]
  pull_request:
    paths: ["core/**", "python/**", "pixi.toml", "pixi.lock"]
  merge_group:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  codegen:
    name: Codegen
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          pixi-version: "latest"
      - name: Prepare pixi
        run: pixi run install-ci
      - name: Test if codegen runs without errors
        run: pixi run codegen
      - name: Ensure that no code has been generated
        run: git diff --exit-code
