name: Python Codegen
on:
  push:
    branches: [main]
    paths: ["core/**", "python/**", "pixi.toml", "pixi.lock"]
    tags: ["*"]
  pull_request:
    paths: ["core/**", "python/**", "pixi.toml", "pixi.lock"]
  merge_group:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  codegen:
    name: Codegen
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          pixi-version: "latest"
      - name: Test if codegen runs without errors
        run: pixi run codegen
      - name: Ensure that no code has been generated
        run: git diff --exit-code
