name: Ribasim Python Tests
on:
  push:
    branches: [main]
    paths: ["python/**", "pixi.toml", "pixi.lock"]
    tags: ["*"]
  pull_request:
    paths: ["python/**", "pixi.toml", "pixi.lock"]
  merge_group:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  test:
    name: ${{ matrix.pixi-environment }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        pixi-environment:
          - default
          - py312
          - pandas2
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
        with:
          pixi-version: "latest"
      - name: Test Ribasim Python
        run: pixi run --environment ${{ matrix.pixi-environment }} test-ribasim-python-cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
